### ISSUE TITLE
salt-api: RuntimeError: Please set SaltAPI._default_logging_logfile_

### ISSUE THREAD

**Issue by m87carlson** [vmware-archive/salt-api#111]
When I try to run salt-api, it reports that I need to set SaltAPI._default_logging_logfile_:

```

# salt-api
Traceback (most recent call last):
  File "/usr/local/bin/salt-api", line 11, in <module>
    main()
  File "/usr/local/bin/salt-api", line 7, in main
    sapi = saltapi.cli.SaltAPI()
  File "/usr/local/lib/python2.7/site-packages/salt/utils/parsers.py", line 113, in __init__
    optparse.OptionParser.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/optparse.py", line 1219, in __init__
    add_help=add_help_option)
  File "/usr/local/lib/python2.7/site-packages/salt/utils/parsers.py", line 178, in _populate_option_list
    mixin_setup_func(self)
  File "/usr/local/lib/python2.7/site-packages/salt/utils/parsers.py", line 308, in _mixin_setup
    self.__class__.__name__
RuntimeError: Please set SaltAPI._default_logging_logfile_
```

I have the log_file set in master, and I do not see any additional documentation on how to explicitly set the log file for the API

System Info:

Platform:

```
FreeBSD salt-1 9.1-RELEASE FreeBSD 9.1-RELEASE #0 r243825: Tue Dec  4 09:23:10 UTC 2012     root@farrell.cse.buffalo.edu:/usr/obj/usr/src/sys/GENERIC  amd64
```

Installed salt-api from ports:

```
pkg info -f py27-salt-api
py27-salt-api-0.8.1
Name           : py27-salt-api
Version        : 0.8.1
Origin         : sysutils/py-salt-api
Prefix         : /usr/local
Categories     : sysutils python
Licenses       : AL2
Maintainer     : christer.edwards@gmail.com
WWW            : http://saltstack.org
Comment        : Exposes the fundamental aspects of Salt control to external sources
Flat size      : 177KiB
Description    :
Salt API : Expose the fundamental aspects of Salt control to external sources
=============================================================================

Salt API is a modular interface on top of Salt that can provide a variety of 
entry points into a running Salt system.

WWW: http://saltstack.org
```

Thanks,
Mike C

**Comment by SmithSamuelM** [comment]
I think this is a bug in an old version of salt.

**Comment by s0undt3ch** [comment]
Nope, this is salt-api using a newer salt. I'll get a PR for this.

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "Samuel Smith" notifications@github.com
Para: "saltstack/salt-api" salt-api@noreply.github.com
Assunto: [salt-api] salt-api: RuntimeError: Please set SaltAPI._default_logging_logfile_ (#111)
Data: ter, Ago 20, 2013 20:35
I think this is a bug in an old version of salt. 

&mdash;

**Comment by s0undt3ch** [comment]
I spoke too soon. This is an older version of salt-api running a newer version of salt. Current develop of salt-api already has the code to handle this.

**Comment by m87carlson** [comment]
Yeah. I locally patched the sysutils/py-salt-api Makefile to fetch 0.8.2
and it worked.

Sorrt for the noise! I can submit a PR for the port.

Mike C

**Comment by m87carlson** [comment]
PR: http://www.freebsd.org/cgi/query-pr.cgi?pr=181440
