### ISSUE TITLE
Race Condition with grains with newly added hosts?

### ISSUE THREAD

**Issue by jalons** [vmware-archive/salt-api#112]
In salt-api 0.82, salt 0.16.0, there appears to be a race condition or similar on newly added hosts if using grains for targeting.  API is forever in debug mode.

Hosts "recently added" - this can be a variable amount of time/runs that I have not been able to pinpoint - without a specific grain will be targeted 'shortly' after their keys are accepted.

Reproduction steps for me are register new host with saltmaster, verify key is present.  Run a grain targeted custom module against the api:

curl -sS masterhost:8000/minions -H 'Accept: application/x-yaml' -H "X-Auth-Token: ${token}" -d client='local' -d tgt='mygrain:*' -d expr_form='grain' -d fun='custom.module' -d arg='foo' -d arg='bar'

And correct hosts are targeted, and command runs.

Accepting key on master (with either salt-key -a 'fqdn' or salt-key -A), ensuring the host does not contain the new grain and rerunning the above command and the newly added host will be targeted as well for an indeterminate amount of time after the key is accepted.  

If a system's key is accepted but that key no longer exists (i.e., a host is created, presents its public key to the salt master but the master never accepts the key, and the host is destroyed, but subsequent to destruction of the host the key is accepted with salt-key -A or salt-key -a 'fqdn') that key will remain in the targeted list as having the grain until the key is permanently removed from the master ('salt-key -d fqdn').

**Comment by whiteinge** [comment]
Are you able to reproduce this behavior using the `salt` CLI program to run the command?

**Comment by jalons** [comment]
No, only via calls to the API.  Separate clients (on different systems) are able to both return the errant hosts, but `salt -G 'mygrain:*' custom.module foo bar` on the salt master will not target the undesired hosts.

**Comment by jalons** [comment]
Closing this issue, as it's not a problem with the API.  This issue is in salt itself, and while I'm unable to find any commits dealing with it, I have heard work is underway to address this (listening for known vs authenticated hosts).

**Comment by whiteinge** [comment]
Thanks for updating this ticket!
