### ISSUE TITLE
Adding more rest-net api

### ISSUE THREAD

**Issue by FrancoTampieri** [vmware-archive/salt-api#113]
Hi!
I would like to know if is possible to add one or more different rest_api, for example I work with django and pyramid, I see that in the docs you chose cherry_py for server and is one of the dependencies that salt-api download when I install it on ubuntu.

is possible to make the rest api modular? I'm glad to help with.

Regards

**Comment by SmithSamuelM** [comment]
The eventual intent is to allow support for other wsgi servers and web framworks.
If you look at salt/client/api.py, you will see a compact modular client interface.  Its still early yet and we are making lots of changes under the hood to support an event bus based UI.

**Comment by whiteinge** [comment]
This is possible now. salt-api was designed to be modular from the start.

There are currently two "netapi modules", the one using CherryPy and another using straight WSGI, Unused netapi modules are not loaded into memory (same as Salt modules). The intent from the beginning was to allow many module types. For example, differing REST implementations as well as differing transport options (xmlrpc, Web sockets, Jabber, etc).

We gladly accept new netapi modules. Both Django and Pyramid would be great additions! I'm happy to help; feel free to reach out on the mailing list or on IRC in #salt or #salt-devel if you have any questions! Do keep an eye on the work @SmithSamuelM mentioned, it will provide a cleaner interface to Salt, but don't let that stop you from jumping in now as everything you need to write a REST API is available now.

**Comment by whiteinge** [comment]
Forgot to mention, there is a (short) document on how to write a netapi module here:

http://salt-api.readthedocs.org/en/latest/topics/netapis/writing.html

And, again, feel free to reach out if you have any questions.

**Comment by FrancoTampieri** [comment]
@whiteinge @SmithSamuelM Thank you very much, I'll take some time to see the documentation :)

Regards

**Comment by FrancoTampieri** [comment]
@whiteinge I'll fork the project and try to develop a pyramid interface

**Comment by whiteinge** [comment]
@drdran Good luck. Let me know if I can help.
