### ISSUE TITLE
salt-api from git g4dd9e97 won't start

### ISSUE THREAD

**Issue by aboe76** [vmware-archive/salt-api#115]
salt-api git version: 0.8.2.40.g4dd9e97
gives the following error:

```
# salt-api -d
Traceback (most recent call last):
  File "/usr/bin/salt-api", line 4, in <module>
    import saltapi.cli
  File "/usr/lib/python2.7/site-packages/saltapi/cli.py", line 20, in <module>
    import saltapi.client
  File "/usr/lib/python2.7/site-packages/saltapi/client.py", line 13, in <module>
    logger = salt.log.logging.getLogger(__name__)
AttributeError: 'module' object has no attribute 'logging'
```

```
git describe:
v0.8.2-40-g4dd9e97
```

**Comment by s0undt3ch** [comment]
The fix is to import logging directly and instantiating from there. Ill

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "Niels Abspoel" notifications@github.com
Para: "saltstack/salt-api" salt-api@noreply.github.com
Assunto: [salt-api] salt-api from git g4dd9e97 won&apos;t start (#115)
Data: qui, Set 12, 2013 18:11
salt-api git version: 0.8.2.40.g4dd9e97

gives the following error: 

# salt-api -d

Traceback (most recent call last): 
File "/usr/bin/salt-api", line 4, in <module> 
import saltapi.cli 
File "/usr/lib/python2.7/site-packages/saltapi/cli.py", line 20, in <module> 
import saltapi.client 
File "/usr/lib/python2.7/site-packages/saltapi/client.py", line 13, in <module> 
logger = salt.log.logging.getLogger(**name**) 
AttributeError: 'module' object has no attribute 'logging' 

git describe: 
v0.8.2-40-g4dd9e97 

&mdash;

**Comment by s0undt3ch** [comment]
Too fast in the trigger...

I'll have a PR shortly...

## 

Pedro Algarvio @ phone

----- Reply message -----
De: "Niels Abspoel" notifications@github.com
Para: "saltstack/salt-api" salt-api@noreply.github.com
Assunto: [salt-api] salt-api from git g4dd9e97 won&apos;t start (#115)
Data: qui, Set 12, 2013 18:11
salt-api git version: 0.8.2.40.g4dd9e97

gives the following error: 

# salt-api -d

Traceback (most recent call last): 
File "/usr/bin/salt-api", line 4, in <module> 
import saltapi.cli 
File "/usr/lib/python2.7/site-packages/saltapi/cli.py", line 20, in <module> 
import saltapi.client 
File "/usr/lib/python2.7/site-packages/saltapi/client.py", line 13, in <module> 
logger = salt.log.logging.getLogger(**name**) 
AttributeError: 'module' object has no attribute 'logging' 

git describe: 
v0.8.2-40-g4dd9e97 

&mdash;

**Comment by aboe76** [comment]
Tested your fix, it didn't work: salt-api version: 0.8.2.42.g5a30e80

```
Traceback (most recent call last):
  File "/usr/bin/salt-api", line 4, in <module>
    import saltapi.cli
  File "/usr/lib/python2.7/site-packages/saltapi/cli.py", line 20, in <module>
    import saltapi.client
  File "/usr/lib/python2.7/site-packages/saltapi/client.py", line 13, in <module>
    logger = salt.log.logging.getLogger(__name__)
AttributeError: 'module' object has no attribute 'logging'
```

**Comment by aboe76** [comment]
tested it again: 
version: 0.8.2.44.g21748a9

@s0undt3ch everything is working again, thank you for your time.

**Comment by sebw** [comment]
Hmm the salt-api package in EPEL has not been updated since July, and still contains this bug :(

**Comment by whiteinge** [comment]
Thanks for the note. It's well past time to cut a release. I'll start working on that over the weekend.

**Comment by whiteinge** [comment]
Release cut and uploaded to PyPI. I won't announce it on the list for a day or two while packages are being built.

**Comment by aboe76** [comment]
building for suse as I wrote this...should be done by tommorow, opensuse factory should follow soon behind release in devel:language:python repo.

**Comment by whiteinge** [comment]
Much obliged, good sir!

**Comment by deuscapturus** [comment]
This problem persists.  Installed salt-api from EPEL on Amazon Linux AMI release 2014.03.

salt-api-0.8.2-0.el6.noarch

```
[root@ip-10-1-0-116 ec2-user]# service salt-api start
Starting salt-api daemon: Traceback (most recent call last):
  File "/usr/bin/salt-api", line 4, in <module>
    import saltapi.cli
  File "/usr/lib/python2.6/site-packages/saltapi/cli.py", line 20, in <module>
    import saltapi.client
  File "/usr/lib/python2.6/site-packages/saltapi/client.py", line 13, in <module>
    logger = salt.log.logging.getLogger(__name__)
AttributeError: 'module' object has no attribute 'logging'
                                                           [FAILED]
```

**Comment by s0undt3ch** [comment]
salt-api is now merged into salt itself and will be released in the next major release v2014.7.0. If you wish, v2014.7.0rc2 has been released recently...
Anyway, before the merge, 0.8.4.1 was released and should include the fix. EPEL doesn't ship a more recent `salt-api`?

**Comment by whiteinge** [comment]
That is indeed quite old. EPEL hasn't been updated with the current
release. There is an rpm of the latest release in the releases tab of this
repo. (Can't seem to link it from my phone.)

**Comment by s0undt3ch** [comment]
https://github.com/saltstack/salt-api/releases/download/v0.8.4.1/salt-api-0.8.4.1-1.el6.noarch.rpm

**Comment by deuscapturus** [comment]
Thanks!  I'll use this until v2014.7 is available in the EPEL.
