### ISSUE TITLE
rest_cherrypy WSGI script under Apache2+mod_wsgi returns ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by threehundobaud** [vmware-archive/salt-api#118]
The following can be seen in the apache error log when attempting to use this from current release:

[Wed Sep 18 15:03:03 2013] [error] [client x.x.x.x] mod_wsgi (pid=23984): Target WSGI script '/usr/lib/python2.7/dist-packages/saltapi/netapi/rest_cherrypy/wsgi.py' cannot be loaded as Python module.
[Wed Sep 18 15:03:03 2013] [error] [client x.x.x.x] mod_wsgi (pid=23984): Exception occurred processing WSGI script '/usr/lib/python2.7/dist-packages/saltapi/netapi/rest_cherrypy/wsgi.py'.
[Wed Sep 18 15:03:03 2013] [error] [client x.x.x.x] Traceback (most recent call last):
[Wed Sep 18 15:03:03 2013] [error] [client x.x.x.x]   File "/usr/lib/python2.7/dist-packages/saltapi/netapi/rest_cherrypy/wsgi.py", line 44, in <module>
[Wed Sep 18 15:03:03 2013] [error] [client x.x.x.x]     from . import app
[Wed Sep 18 15:03:03 2013] [error] [client x.x.x.x] ValueError: Attempted relative import in non-package

**Comment by whiteinge** [comment]
Thanks for the report! We'll get this fixed for the next release.

**Comment by whiteinge** [comment]
Yikes. Sorry this one got past me for 0.8.3.
