### ISSUE TITLE
Problems with version string

### ISSUE THREAD

**Issue by wari** [vmware-archive/salt-api#121]
Hi there. I just created a new virtualenv, then a simple `pip install salt` just so I can start testing development/playing with salt. This installs version 0.17.1. I know you guys wanted to change the versioning of the product to a date based one, but I can't seem to even do a simple `import salt` on the python REPL on the virtualenv:

``` python
Python 2.7.4 (default, Sep 26 2013, 03:20:26) 
[GCC 4.7.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wari/venv/local/lib/python2.7/site-packages/salt-0.17.1-py2.7.egg/salt/__init__.py", line 27, in <module>
    from salt.version import __version__
  File "/home/wari/venv/local/lib/python2.7/site-packages/salt-0.17.1-py2.7.egg/salt/version.py", line 269, in <module>
    __version__, __version_info__ = __get_version(__version__, __version_info__)
  File "/home/wari/venv/local/lib/python2.7/site-packages/salt-0.17.1-py2.7.egg/salt/version.py", line 229, in __get_version
    parsed_version = SaltStackVersion.parse(out)
  File "/home/wari/venv/local/lib/python2.7/site-packages/salt-0.17.1-py2.7.egg/salt/version.py", line 83, in parse
    'Unable to parse version string: {0!r}'.format(version_string)
ValueError: Unable to parse version string: 'v20131009-9-g40fa813'
```

PS: I know this does not happen if I just use the standard salt bootstrap methods, for example, on another host:

``` python
Python 2.7.3 (default, Sep 26 2013, 20:08:41) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt
>>> salt.__version__
'0.17.1'
```

So is there a way to clear out this error?

**Comment by wari** [comment]
After reading salt/version.py, it seems that having your venv inside your git repo (even if it's not checked in) will cause this error. Anyway, should this be a bug? If not, close it then. Thanks.

Another thing of note. `pip install salt` does not install everything that `easy_install salt` does. Packages like `markupsafe`, `pyyaml`, `msgpack` is not installed when using `pip`

**Comment by wari** [comment]
So sorry, I _was_ trying to run the simple wsgi server, when I got the salt error. And notice the problem was with salt. Except that this issue is reported in the wrong area.. Oops.

**Comment by whiteinge** [comment]
I haven't tried running with a venv inside the Salt checkout (though I have tried with Salt in a venv). When you file an issue on the Salt repo the people that maintain version.py will see it.

Thanks for commenting here with an update.
