### ISSUE TITLE
How to write my own netapi

### ISSUE THREAD

**Issue by wari** [vmware-archive/salt-api#122]
Hi there, say I'd like to create my own API calls to salt. And maybe place this somewhere outside of saltapi.netapi, say in `/srv/someproject/systats/some_rest_api_interface.py`.

The docs does not mention this, but how do I get salt/salt-api to see that this exists?

For now, I know the basics just need a `__virtual__()`, a `start()`, and somehow, there will be a `__opts__` available.

Sorry if I've overlooked at some aspects of the documentation here.

Thanks

**Comment by whiteinge** [comment]
At the moment you need to put your `.py` file in the `netapi` directory where salt-api was installed. We're in the process of merging salt-api into Salt proper and when that is complete it should be trivial to add a `_netapi` directory inside `file_roots` like you can with custom execution or state modules.

**Comment by wari** [comment]
Thanks for the update. I am looking forward to the merge.

**Comment by holmboe** [comment]
@whiteinge oh nice to hear about the pending merge into Salt. :dancers:
