### ISSUE TITLE
Throw a helpful log entry rather than a 500 error on no match

### ISSUE THREAD

**Issue by jalons** [vmware-archive/salt-api#125]
Attempt to target something that doesn't match, salt-api returns a 500 error.

**Comment by whiteinge** [comment]
Can you please include the command you are running to produce this error? What version of salt-api are you on?

**Comment by jalons** [comment]
Hi,

salt-api-0.8.2-0.el6.noarch.

``` bash
curl -sS $saltmaster:8000/minions -H "Accept: application/x-yaml" -H "X-Auth-Token: ${token}" -d client="local" -d tgt="fakegrain:*" -d expr_form='grain' -d fun="test.ping" -d timeout="10"
```

This will throw a 500, as it appears no jid is being generated since no match, and the API is expecting a jid.

**Comment by whiteinge** [comment]
Your diagnosis is spot-on. Thanks for the report and the detail!
