### ISSUE TITLE
Only first request handled properly, others are answered with Error 500

### ISSUE THREAD

**Issue by syphernl** [vmware-archive/salt-api#127]
For some reason only the first request ever made to a fresh Salt-API process is being dealt with properly. For others its throwing an HTTP 500 error.

For instance, if the first request is:

```
curl -sSi localhost:8000/minions \
    -H "Accept: application/x-yaml" \
    -d tgt='*' \
    -d fun='status.diskusage'
```

It properly returns that the user should login first:

```
HTTP/1.1 401 Unauthorized
Content-Length: 47
Vary: Accept-Encoding
Server: CherryPy/3.2.2
Allow: GET, HEAD, POST
Date: Fri, 15 Nov 2013 08:03:54 GMT
Access-Control-Allow-Origin: *
Content-Type: application/x-yaml
Www-Authenticate: Session
Set-Cookie: session_id=0088a50c8bea2b48ed26f69e40ab335a6e1e6b81; expires=Fri, 15 Nov 2013 18:03:54 GMT; Path=/

return: Please log in
status: 401 Unauthorized
```

Ok, so lets login then:

Request:

```
 curl -si localhost:8000/login \
        -H "Accept: application/json" \
        -d username='salt' \
        -d password='verysecret' \
        -d eauth='pam'
```

Response:

```
HTTP/1.1 500 Internal Server Error
Content-Length: 805
X-Auth-Token: c842418e46ef9af46e75e441eb6cc3ff536x6x5x
Allow: GET, HEAD, POST
Date: Fri, 15 Nov 2013 08:04:52 GMT
Access-Control-Allow-Origin: *
Server: CherryPy/3.2.2
Content-Type: text/html;charset=utf-8
Set-Cookie: session_id=c842418e46ef9af46e75e441eb6cc3ff536x6x5x; expires=Fri, 15 Nov 2013 18:04:52 GMT; Path=/

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.2</a></span>
    </div>
    </body>
</html>
```

So, we do get an X-Auth-Token returned but also an error which causes the client to assume something went wrong (which is the correct way of validating rather than checking whether we did get an X-Auth-Token in return or not)

The console at trace level shows:

```
[INFO    ] 127.0.0.1 - - [15/Nov/2013:09:04:52] "POST /login HTTP/1.1" 500 805 "" "curl/7.32.0"
[ERROR   ] [15/Nov/2013:09:04:52]  Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 102, in run
    hook()
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 62, in __call__
    return self.callback(**self.kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/sessions.py", line 706, in close
    sess.release_lock()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/sessions.py", line 374, in release_lock
    self.locks[self.id].release()
KeyError: u'c842418e46ef9af46e75e441eb6cc3ff536x6x5x'

[ERROR   ] [15/Nov/2013:09:04:52]  Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cptree.py", line 140, in release_serving
    req.close()
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 492, in close
    self.hooks.run('on_end_request')
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 112, in run
    raise exc
KeyError: u'c842418e46ef9af46e75e441eb6cc3ff536x6x5x'
```

Version report:

```
           Salt: 0.17.1
         Python: 2.7.5+ (default, Sep 19 2013, 13:49:51)
         Jinja2: 2.7
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.5
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.3
```

And the API itself is salt-api 0.8.3 (git cloned, 4c9faa7485f3acdbee2557cb0c690eec91544589)

The Salt user is authorised in the master config:

```
external_auth:
  pam:
    salt:
         - .*
```

and this is the config I use for the cherrypy:

```
rest_cherrypy:
  port: 8000
  disable_ssl: True
```

Seems like a bug to me, but I'm not familiar (yet) with the Salt-API code so hoping someone can shed some light on this. If you need more information, please let me know.

**Comment by syphernl** [comment]
I had it set up somewhere else before, which had a similar setup but appears to have been using 40cb5e3b0dc52232f83fe7af85a6e23e554a379b. Hopefully that can help you narrow down what went wrong. 

Versions are slightly different too though because this one is on Ubuntu 12.04 while the other is on 13.10. Maybe it'll help, so here are the versions of that one:

```
           Salt: 0.17.1
         Python: 2.7.3 (default, Sep 26 2013, 20:03:06)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.10
          PyZMQ: 13.0.0
            ZMQ: 3.2.2
```

Seems like the only change in between (besides manpages/docs/releasenotes/comments etc) is 03fbaf55367441b2f45a76c3066eff6be0a6c873

**Comment by whiteinge** [comment]
Thanks.

**Comment by whiteinge** [comment]
I haven't been able to reproduce this error yet.

Is the token that is returned as part of the 500 response a valid token? Can you use it to run a test.ping execution using that token after seeing the 500?

If you login as the first step instead of trying to run an execution first does it still return a 500?

**Comment by syphernl** [comment]
Authenticating first seems to work with test.ping. I can run multiple commands with no problem.

However, authenticating twice in a row results in the same error as described.

The token mentioned in the error is valid though.

**Comment by syphernl** [comment]
With the cookie-login I've also managed to get KeyErrors. Probably because the application used an cookie with a token that was not valid anymore after the Salt API daemon was restarted.

**Comment by whiteinge** [comment]
@syphernl Sorry for the slow response on this one. I cannot reproduce this error no matter how I try. I've matched Salt, salt-api, and CherryPy versions with what you have. I've tried various combinations of ordering login and execution. I've tried erasing the session table between attempts. Nothing. I'm not sure what to try next. Are you still seeing the problem? Perhaps a screen-share session?

**Comment by syphernl** [comment]
@whiteinge I'll see if I can build a fresh VM with master + api, but screen sharing is fine too. What do you have in mind for that?

**Comment by whiteinge** [comment]
Something easy like a quick Google hangout?

**Comment by syphernl** [comment]
That sounds good @whiteinge, just let me know when you have time. Note that we do have an 8h time difference though.

FWIW I was just able to reproduce it again (at the same machine though, currently setting up a fresh test machine) by simply sending a second login request with the command mentioned in the first reply.

**Comment by syphernl** [comment]
This is so weird/frustrating: A fresh VM (same versions) does not have this issue. 
The only difference is that the "bugged" one is running Cherrypy 3.2.2 and the other one gets 3.2.4 when installed via `easy_install`

Updating the 'bugged" server with that one.. no effect.

**Comment by whiteinge** [comment]
How odd. Both 3.2.2 and 3.2.4 should work. I've tested with both anyway.

Does the following command output the version you're expecting on the bugged system? I wonder if perhaps there's a second old/broken installation of CherryPy on the system.

``` bash
python -c "import cherrypy; print cherrypy.__version__"
```

**Comment by syphernl** [comment]
Yes, that returns the system-wide installed version of Cherrypy: 3.2.4.

**Comment by whiteinge** [comment]
I wonder if the installation is borked somehow. easy_install doesn't do
uninstall but you could try manually blowing away
/usr/lib/python2.7/dist-packages/cherrypy/ and reinstalling. If that
doesn't help let's do a Hangout after the holidays.

**Comment by syphernl** [comment]
With changing versions / reinstalling it the messages have changed a bit but it is still broken, not sure if it helps narrow down things a bit more (probably not, but worth a shot)

Request response:

```
HTTP/1.1 500 Internal Server Error
Content-Length: 1178
X-Auth-Token: 5f9a391daaaacb4a7e4d0051a4c08a601af19842
Allow: GET, HEAD, POST
Date: Wed, 25 Dec 2013 12:55:07 GMT
Access-Control-Allow-Origin: *
Server: CherryPy/3.2.4
Content-Type: text/html;charset=utf-8
Set-Cookie: session_id=5f9a391daaaacb4a7e4d0051a4c08a601af19842; expires=Wed, 25 Dec 2013 22:55:07 GMT; Path=/

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cprequest.py", line 660, in respond
    self.hooks.run('before_finalize')
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cprequest.py", line 112, in run
    raise exc
KeyError: u'5f9a391daaaacb4a7e4d0051a4c08a601af19842'
</pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.4</a></span>
    </div>
    </body>
</html>
```

API process:

```
[25/Dec/2013:13:57:30]  Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cprequest.py", line 102, in run
    hook()
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cprequest.py", line 62, in __call__
    return self.callback(**self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/lib/sessions.py", line 698, in save
    cherrypy.session.save()
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/lib/sessions.py", line 230, in save
    self.release_lock()
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/lib/sessions.py", line 374, in release_lock
    self.locks[self.id].release()
KeyError: u'c87319614b5b4cb4dfcc999bab5c5335dc44ea6e'

[ERROR   ] [25/Dec/2013:13:57:30]  Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cprequest.py", line 102, in run
    hook()
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cprequest.py", line 62, in __call__
    return self.callback(**self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/lib/sessions.py", line 698, in save
    cherrypy.session.save()
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/lib/sessions.py", line 230, in save
    self.release_lock()
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/lib/sessions.py", line 374, in release_lock
    self.locks[self.id].release()
KeyError: u'c87319614b5b4cb4dfcc999bab5c5335dc44ea6e'

[25/Dec/2013:13:57:30] HTTP
Request Headers:
  Content-Length: 45
  HOST: localhost:8000
  Remote-Addr: 127.0.0.1
  ACCEPT: application/json
  USER-AGENT: curl/7.32.0
  Content-Type: application/x-www-form-urlencoded
[INFO    ] [25/Dec/2013:13:57:30] HTTP
Request Headers:
  Content-Length: 45
  HOST: localhost:8000
  Remote-Addr: 127.0.0.1
  ACCEPT: application/json
  USER-AGENT: curl/7.32.0
  Content-Type: application/x-www-form-urlencoded
[25/Dec/2013:13:57:30] HTTP Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cprequest.py", line 660, in respond
    self.hooks.run('before_finalize')
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cprequest.py", line 112, in run
    raise exc
KeyError: u'c87319614b5b4cb4dfcc999bab5c5335dc44ea6e'

[ERROR   ] [25/Dec/2013:13:57:30] HTTP Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cprequest.py", line 660, in respond
    self.hooks.run('before_finalize')
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cprequest.py", line 112, in run
    raise exc
KeyError: u'c87319614b5b4cb4dfcc999bab5c5335dc44ea6e'

127.0.0.1 - - [25/Dec/2013:13:57:30] "POST /login HTTP/1.1" 500 1178 "" "curl/7.32.0"
[INFO    ] 127.0.0.1 - - [25/Dec/2013:13:57:30] "POST /login HTTP/1.1" 500 1178 "" "curl/7.32.0"
[25/Dec/2013:13:57:30]  Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cprequest.py", line 102, in run
    hook()
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cprequest.py", line 62, in __call__
    return self.callback(**self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/lib/sessions.py", line 706, in close
    sess.release_lock()
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/lib/sessions.py", line 374, in release_lock
    self.locks[self.id].release()
KeyError: u'c87319614b5b4cb4dfcc999bab5c5335dc44ea6e'

[ERROR   ] [25/Dec/2013:13:57:30]  Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cprequest.py", line 102, in run
    hook()
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cprequest.py", line 62, in __call__
    return self.callback(**self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/lib/sessions.py", line 706, in close
    sess.release_lock()
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/lib/sessions.py", line 374, in release_lock
    self.locks[self.id].release()
KeyError: u'c87319614b5b4cb4dfcc999bab5c5335dc44ea6e'

[25/Dec/2013:13:57:30]  Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cptree.py", line 140, in release_serving
    req.close()
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cprequest.py", line 492, in close
    self.hooks.run('on_end_request')
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cprequest.py", line 112, in run
    raise exc
KeyError: u'c87319614b5b4cb4dfcc999bab5c5335dc44ea6e'

[ERROR   ] [25/Dec/2013:13:57:30]  Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cptree.py", line 140, in release_serving
    req.close()
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cprequest.py", line 492, in close
    self.hooks.run('on_end_request')
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cprequest.py", line 112, in run
    raise exc
KeyError: u'c87319614b5b4cb4dfcc999bab5c5335dc44ea6e'
```

We can further troubleshoot this, but if no one else has it it must be something local which I'll just have to live with. The issue has been mitigated by switching to cookies instead of logging in for each request, I could switch to uwsgi+nginx for API serving and bypass the whole Cherrypy which might be another option.

If you think it is still worth to investigate further, I'm available for a Hangout to do so. 
Just let me know, I'm also on IRC so you can also ping me there.

**Comment by syphernl** [comment]
Any chance we can revisit this any time soon @whiteinge ? I have been working on a new API wrapper for my project which caches the token until it expires (long live Redis with a TTL) and requests a new one. Same for when a 401 is given.

However. After some time (it could be after the initial expiry) I am seeing in the API debug that it is indeed using a new token after a while but it results in the same error every time with a varying key. Sounds like something is still stuck somewhere in the process. I have updated all Python modules Salt used to the latests versions available:

```
           Salt: 2014.1.0-1174-gb56278f
         Python: 2.7.5+ (default, Sep 19 2013, 13:49:51)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.3
```

This has no effect on this behavior unfortunately. Cherrypy is (still) at 3.2.4.

**Comment by whiteinge** [comment]
@syphernl Yeah, let's do a hangout and get this figured out. I just sent you an email.

**Comment by syphernl** [comment]
So, to summarize our Hangout we had earlier (really appreciate that by the way!):
- With 1 token active: no problem. Client works as it should
- When the token expires and a new one is requested all requests fail and keep failing

---
- With 1 token active: No problem. Client works as it should
- Other client/app becomes active and requests a token of his own, without the other one being expired all requests of the second client/app fails while the first one continues on (until its ttl has been reached)

This all runs on Ubuntu 13.10 on x86 with the versions mentioned above (with the difference is that Salt has been upgraded to `Salt 2014.1.0-1293-gd266d46`)

If there is anything you'd like me to test/provide please let me know! Thanks again!

**Comment by whiteinge** [comment]
Thanks for posting a recap. I haven't been able to recreate with multiple concurrent users. I'm poking at expiring tokens now....

**Comment by toomuchcoffeecoder** [comment]
I am having the same problem on a GoDaddy Windows VPS with with cherrypy 3.2.5 and python 3.3.5 

  File "C:\Python33\lib\site-packages\cherrypy\lib\sessions.py", line 706, in close
    sess.release_lock()
  File "C:\Python33\lib\site-packages\cherrypy\lib\sessions.py", line 374, in release_lock
    self.locks[self.id].release()
KeyError: '17d0d2b6c94be600a15e9431e968e504011bfaab'

Followed by a timeout error.
Running locally on a Windows 7 desktop I don't have this problem but on the VPS I do.

**Comment by whiteinge** [comment]
@toomuchcoffeecoder salt-api should not work on Python 3 or Windows because the Salt master does not yet run on Python 3 or Windows.

**Comment by syphernl** [comment]
It looks like this problem is solved, key expiry and logging in again works fine now!

**Comment by whiteinge** [comment]
@syphernl I am very glad to hear that! I wish we could have found the cause though...

**Comment by syphernl** [comment]
True. Well, the dependencies have not been updated any time recently but salt-api has, perhaps one of the changes done lately have a positive effect on this?
