### ISSUE TITLE
Traceback not treated as error

### ISSUE THREAD

**Issue by syphernl** [vmware-archive/salt-api#132]
I was doing [ps.top](https://github.com/saltstack/salt/issues/9274) via the HTTP API, which failed and returned traceback.

If a module execution fails (with traceback) it should set the appropriate values in the HTTP headers indicating that the request has failed so the API client can properly handle the error.

**Comment by whiteinge** [comment]
I agree something like this would be useful but it would hard to implement correctly. For example, say you run `ps.top` on ten machines and all but one return successfully. We can only return one status code for the execution on all ten minions. This exact dilemma also exists at the CLI when running the `salt` command -- what should the exit code be? I'm not sure this can be improved on at the HTTP status code or CLI exit code level, but perhaps there are things we can add to make the output easier to parse (visually or programmatically) for errors.

If you have any ideas on how to improve this, I'd love to hear them.

**Comment by syphernl** [comment]
Hmm didn't think of that. But it doesn't matter whether 1 of 100 minions report a failure: the API should never send pure tracebacks as a response, it should include something that the client can interpret as an error. 

If there is only one minion targeted (like what was the case for me when this error occurred) it could properly set the response code. 

Perhaps we should add a "status(code)" field and put the data in "output" / "data" or something like that. Or a count field with properly completed requests, the client can then check if the amount of success matches the one for the request.

**Comment by whiteinge** [comment]
I like your idea of adding summary info to the return. Status field, success/failure counts, etc. Currently Salt's Python API (that salt-api wraps) returns tracebacks from minions as strings; salt-api could just iterate over the result looking for traceback text but perhaps there's something we could add to Salt to make that less hack-ish (plus that would also be useful info to have available at the CLI). I think a little code-diving is in order...
