### ISSUE TITLE
Add a generic entry-point for use as a web hook

### ISSUE THREAD

**Issue by whiteinge** [vmware-archive/salt-api#135]
salt-api is a logical entry point for a Salt system to receive HTTP requests for web hooks (think GitHub, Travis-CI). It should fire an event so that Salt can take some action.

How should the incoming HTTP request be verified?

**Comment by s0undt3ch** [comment]
Nicely thought!

**Comment by whiteinge** [comment]
Added in a5dcdad8a4d1.

**Comment by whiteinge** [comment]
Documented here:

http://salt-api.readthedocs.org/en/latest/ref/netapis/all/saltapi.netapi.rest_cherrypy.html#saltapi.netapi.rest_cherrypy.app.Webhook
