### ISSUE TITLE
get error when start salt-api [ERROR   ] Not loading 'rest_wsgi'. 'port' not specified in config

### ISSUE THREAD

**Issue by justlooks** [vmware-archive/salt-api#141]
# service salt-api start

Starting salt-api daemon: [ERROR   ] Not loading 'rest_wsgi'. 'port' not specified in config
[06/Mar/2014:09:20:31] ENGINE Listening for SIGHUP.
[06/Mar/2014:09:20:31] ENGINE Listening for SIGTERM.
[06/Mar/2014:09:20:31] ENGINE Listening for SIGUSR1.
[06/Mar/2014:09:20:31] ENGINE Bus STARTING
CherryPy Checker:
'log_file' is obsolete. Use 'log.error_file' instead.
section: [saltopts]

[06/Mar/2014:09:20:31] ENGINE Started monitor thread '_TimeoutMonitor'.
[06/Mar/2014:09:20:31] ENGINE Started monitor thread 'Autoreloader'.
[06/Mar/2014:09:20:31] ENGINE Serving on 0.0.0.0:8888
[06/Mar/2014:09:20:31] ENGINE Bus STARTED

**Comment by whiteinge** [comment]
That `rest_wsgi` error message is from Salt's loader system. It can be safely ignored. It it just informing you that it did not load that module into memory. That module is more of an example and is not recommended for most use.

It looks like you are successfully starting the `rest_cherrypy` module though so you should have a functioning REST interface on port 8888.

**Comment by davebo** [comment]
An error should not be created if there is no error.  "Safe to ignore" is a dangerous trap.  If it is warning about not loading  the module, make it a warning, not an error.

**Comment by whiteinge** [comment]
Great point. Looking again, this logging call was a copy-and-paste from the `rest_cherrypy` module but it missed the conditional check from that logging. There's no need to have it in this module at all.

Thanks for filing this, @justlooks. And thanks for pointing out my mistake, @davebo.
