### ISSUE TITLE
Use PHP to call API ,produce 400 Bad Request：Lowstates must be a list

### ISSUE THREAD

**Issue by ivanwa** [vmware-archive/salt-api#142]
An error message:
400 Bad Request

Lowstates must be a list

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.6/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/usr/lib/python2.6/site-packages/saltapi/netapi/rest_cherrypy/app.py", line 273, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(_args, *_kwargs)
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/usr/lib/python2.6/site-packages/saltapi/netapi/rest_cherrypy/app.py", line 1074, in POST
    'return': list(self.exec_lowstate()),
  File "/usr/lib/python2.6/site-packages/saltapi/netapi/rest_cherrypy/app.py", line 490, in exec_lowstate
    raise cherrypy.HTTPError(400, 'Lowstates must be a list')
HTTPError: (400, 'Lowstates must be a list')

---

And I use the command line to run, but it can be successful.
[root@localhost salt]# curl -k https://192.168.1.159:8000/run/ \

> ```
>  -H "Accept: application/x-yaml" \
>  -d username='saltapi' \
>  -d password='123456' \
>  -d eauth='pam' \
>  -d client='local' \
>  -d tgt='*' \
>  -d fun='test.ping'
> ```
> 
> return:
> - {}

---

My PHP script : index.php
$url = "https://192.168.1.159:8000/run";
$post_data = array (
        "username" => "saltapi",
        "password" => "123456",
        "eauth" => "pam",
        "client" => "local",
        "tgt" => "*",
        "fun" => "test.ping",
        "arg"=>""
);
$ch = curl_init ();
curl_setopt ( $ch, CURLOPT_URL, $url );
curl_setopt ( $ch, CURLOPT_SSL_VERIFYPEER, false );
curl_setopt ( $ch, CURLOPT_SSL_VERIFYHOST, false );
curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-type: application/x-www-form-urlencoded",'Expect:'));
curl_setopt ( $ch, CURLOPT_RETURNTRANSFER, 1 );

curl_setopt ( $ch, CURLOPT_POST, 1 );
curl_setopt ( $ch, CURLOPT_POSTFIELDS, $post_data );
$output = curl_exec ( $ch );
curl_close ( $ch );
// print
print_r ( $output );

---

My master:
interface: 192.168.1.159

rest_cherrypy:
  host: 0.0.0.0
  port: 8000
  debug: true
  static: /salt-webui/halite/halite
  app: /salt-webui/halite/halite
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/private/localhost_nopass.key

external_auth:
  pam:
    saltapi:
      - .*

**Comment by whiteinge** [comment]
What version of salt-api are you running so I can try to duplicate with that same version?

Side note regarding your config: Halite does not use salt-api so your "static" and "app" entries there won't work for Halite.

**Comment by ivanwa** [comment]
whiteinge,thanks for you reply.

## I'm looking forward to your reply again.

Here is my program version:
CentOS 6.4 X64
[root@localhost salt]# pip list
Babel (0.9.4)
CherryPy (3.2.5)
iniparse (0.3.1)
Jinja2 (2.2.1)
M2Crypto (0.20.2)
msgpack-python (0.1.13)
pip (1.5.4)
pycrypto (2.0.1)
pycurl (7.19.0)
pygpgme (0.1)
PyYAML (3.10)
pyzmq (2.2.0.1)
salt (2014.1.0)
salt-api (0.8.3-47-g0a12f8b)
setuptools (3.1)
urlgrabber (3.9.1)
yum-metadata-parser (1.1.2)

**Comment by ivanwa** [comment]
I find a solution.In php script,post data can't be an array.
I change the format.
Like this:$postdata="username='saltapi'&password='123456'&eauth='pam'";
And the last run successfully.
Finally, thank you again for whiteinge.
