### ISSUE TITLE
Access to services not in real time

### ISSUE THREAD

**Issue by ivanwa** [vmware-archive/salt-api#145]
![image](https://f.cloud.github.com/assets/6895983/2457526/ed51f13e-af38-11e3-8f60-957be4c032b1.png)
I confirm that the service is already running,But the salt can't detect.
My software version:
Babel (0.9.4)
CherryPy (3.2.5)
iniparse (0.3.1)
Jinja2 (2.2.1)
M2Crypto (0.20.2)
msgpack-python (0.1.13)
pip (1.5.4)
pycrypto (2.0.1)
pycurl (7.19.0)
pygpgme (0.1)
PyYAML (3.10)
pyzmq (2.2.0.1)
salt (2014.1.0)
salt-api (0.8.3-47-g0a12f8b)
setuptools (3.1)
urlgrabber (3.9.1)
yum-metadata-parser (1.1.2)

minion:
windows server 2008 R2
Salt-Minion-2014.1.0-AMD64-Setup.exe

**Comment by wari** [comment]
I believe this is the wrong repo to report this to. See: https://github.com/saltstack/salt

**Comment by syphernl** [comment]
Wrong repo indeed (as the screenshot indicates CLI/generic salt stuff rather than the api) and probably the wrong command too. Enabled is to check if is set to run onboot, you should use service.running to check if services are running or not.
