### ISSUE TITLE
Login very slow

### ISSUE THREAD

**Issue by ivanwa** [vmware-archive/salt-api#151]
![image](https://cloud.githubusercontent.com/assets/6895983/2872692/4d124968-d372-11e3-99ae-d4837a0d6fe7.png)
I found the login speed related to the version.In 0.8.4.1,login use around 30 seconds,and the 0.8.3 use around 25 seconds.
But these are a little too long, so I want to ask what is the method.

version centos6.5 x64
[root@localhost init.d]# pip list
Babel (0.9.4)
Beaker (1.3.1)
CherryPy (3.2.2)
cups (1.0)
cupshelpers (1.0)
decorator (3.0.1)
ethtool (0.6)
firstboot (1.110)
iniparse (0.3.1)
iwlib (1.0)
Jinja2 (2.2.1)
M2Crypto (0.20.2)
Mako (0.3.4)
MarkupSafe (0.9.2)
msgpack-python (0.1.13)
pip (1.5.4)
pycrypto (2.0.1)
pycurl (7.19.0)
pygpgme (0.1)
python-meh (0.11)
PyYAML (3.10)
pyzmq (2.2.0.1)
salt (2014.1.3)
salt-api (0.8.4.1)
scdate (1.9.60)
setuptools (3.4.4)
slip (0.2.20)
slip.dbus (0.2.20)
smbc (1.0)

**Comment by whiteinge** [comment]
That is unusually slow. It should be nearly instant. Can you reproduce that
behavior with Salt at the CLI?

salt -a pam '*' test.ping

**Comment by ivanwa** [comment]
@whiteinge I found that, as long as with the account password, we will be very slow.
![image](https://cloud.githubusercontent.com/assets/6895983/2874710/b7494efe-d3f8-11e3-961d-f22e6816ecc0.png)
![image](https://cloud.githubusercontent.com/assets/6895983/2874759/328182ba-d3fb-11e3-9480-aa6514e635df.png)

However, the use of token reaction is very fast.
![image](https://cloud.githubusercontent.com/assets/6895983/2874756/f67149b8-d3fa-11e3-97a4-86c99d3da9f2.png)

**Comment by whiteinge** [comment]
salt-api doesn't hit the underlying PAM system for as long as a token is
valid so that part makes sense to me -- the check is all in RAM.

Is there anything unusual about your PAM set-up? Is there any network
component like LDAP or NFS?

**Comment by ivanwa** [comment]
@whiteinge I found the problem!PAM is not the problem.The reason is that I set up  salt - API on boot, it cause unusually slow.After I restart the service, everything is very normal!

Now I try to locate to the centos chkconfig service, see if I can find the cause of the abnormal.
When I turn off salt-API on boot, restart the server and start salt - API service,it won't appear unusually slow problem.

My salt-api using script:
https://raw.githubusercontent.com/saltstack/salt-api/v0.8.4.1/pkg/rpm/salt-api

**Comment by whiteinge** [comment]
How odd! I'm glad you have a workaround for now. I can't think what the
problem might be. What OS and version are you running?

**Comment by ivanwa** [comment]
@whiteinge  In vmware 10.0.2~~My testing machine.
![image](https://cloud.githubusercontent.com/assets/6895983/2885459/7dec4ace-d4c2-11e3-917b-38b6e1484dce.png)

I just updated salt2014.1.4,all problems are solved.

Then I'll change the environment in the test, to see if that happens.
Take a look at when salt2014.1.3+salt-api0.8.3 /0.8.4.1 ,it will cause unusually slow?

**Comment by whiteinge** [comment]
Sorry for the slow reply -- I've been traveling. Thanks for the update about the version mismatch. I'm not sure what the issue is but I'll give it a look on those versions.

I'm glad you got it working!
