### ISSUE TITLE
For salt chinese support problem

### ISSUE THREAD

**Issue by ivanwa** [vmware-archive/salt-api#152]
Under my production environment, the use of salt will create many problems in Chinese.The problem is under the Windows default encoding is not use UTF-8.The most important that is we have a lot of  Windows Sever.
Like this:
![qq20140507151508](https://cloud.githubusercontent.com/assets/6895983/2912346/0db78e6a-d677-11e3-9549-12f7974dfd76.png)

Although in a production environment using Chinese (such as Chinese path) is not very scientific, but there are problems left over by history, I hope to have a solution.

**Comment by whiteinge** [comment]
Yeah, that's not good. Will you please open this ticket over in the [salt](https://github.com/saltstack/salt/issues) repo instead? This problem will affect salt-api but it must be fixed in Salt first.

**Comment by whiteinge** [comment]
This issue may be related to saltstack/salt#12611.

**Comment by ivanwa** [comment]
Thanks @whiteinge ! I hope it can be fixed in next version.
