### ISSUE TITLE
cherryPy response timeout setting

### ISSUE THREAD

**Issue by IllegalWalker** [vmware-archive/salt-api#159]
Is there a way to set cherryPy response timeout  value?
I use salt-api to execute some long running tasks, which may take 10~20 minutes, but
cherryPy default response timeout value is 5 minute, causing cherryPy TimeoutError.
But I can not find a way to set cherryPy response timeout value in salt-api configuration file, currently I have to edit  saltapi/netapi/rest_cherrypy/app.py  myself to set cherryPy response timeout value.

**Comment by whiteinge** [comment]
There isn't a config option for that but it would be simple to add.

A temporary workaround for now (beside patching the source) is to run the
job using the local_async client and to poll the job URL.

**Comment by IllegalWalker** [comment]
I think it would be more reasonable to have a timeout option in salt-api configuration file.
I will change my long running tasks to async mode.

**Comment by whiteinge** [comment]
The above pull req should prevent timeouts at all. You can also change the default response timeout per-response so a nice-to-have would be to be able to specify the response timeout you want when making the initial HTTP request. E.g., `{"client": "local", "fun": "state.sls", "arg": "longrunningstate", "http_response": 600}`.
