### ISSUE TITLE
problem closing file descriptors using remote salt execution in rundeck

### ISSUE THREAD

**Issue by albertmfb** [vmware-archive/salt-api#167]
When I configure a job in rundeck through Remote Salt Execution in rundeck interface, i can see that after each execution, the opened file descriptors by the rundeck process for

I note that for each job execution the process caches the needed plugins in /var/tmp/pluginJars and libext/cache directories . The problem is that after use them the process doesnt close the descriptors. With lsof i can see

libext/cache/rundeck-salt-plugin-0.3/aopalliance-1.0.jar (deleted)
libext/cache/rundeck-salt-plugin-0.3/spring-aop-3.2.2.RELEASE.jar (deleted)
libext/cache/rundeck-salt-plugin-0.3/spring-expression-3.2.2.RELEASE.jar (deleted)
libext/cache/rundeck-salt-plugin-0.3/httpcore-4.2.4.jar (deleted)
libext/cache/rundeck-salt-plugin-0.3/commons-io-1.3.2.jar (deleted)
var/tmp/pluginJars/20150528163323000-rundeck-copyfile-plugin-2.4.0.jar (deleted)
var/tmp/pluginJars/20150410104509000-rundeck-localexec-plugin-2.4.0.jar (deleted)
var/tmp/pluginJars/20150223160105000-rundeck-script-plugin-2.4.0.jar (deleted)
var/tmp/pluginJars/20150223160105000-rundeck-stub-plugin-2.4.0.jar (deleted)
var/tmp/pluginJars/20150223160105000-rundeck-script-plugin-2.4.0.jar (deleted)

so the filesystem is increasing rapidly in size.
the only solution until now is restart the rundeck service to free the space.

could it be a bug? any ideas?

Any helpwould be appreciated.

product versions:

```
rundeck-2.4.0-1.1.GA.noarch
salt-master-2014.7.0-3.el6.noarch
salt-api-2014.7.0-3.el6.noarch
rundeck-salt-plugin-0.3.jar
```

**Comment by whiteinge** [comment]
At quick glance it looks like the open files are on the Rundeck side of things and I don't have much working knowledge there. Are you running Rundeck and the salt-master on separate machines? If so, does the salt-master seem affected? You might have better luck with the more knowledgable Rundeck folks, but do ping us back on the main Salt repo if you track the problem to Salt.

**Comment by albertmfb** [comment]
Rundeck and SaltStack are in the same machine. 
SaltStack works fine itself, so I think that the problem could be in rundeck process when loading/unloading plugins,

Thanks for the attention

**Comment by albertmfb** [comment]
Fixed-
https://github.com/rundeck/rundeck/issues/1440

**Comment by whiteinge** [comment]
Thanks for the update.
