### ISSUE TITLE
state.sls always run env=base

### ISSUE THREAD

**Issue by bashhu** [vmware-archive/salt-api#177]
```
[root@test1 ~]# curl  -k https://localhost:8000 \
> -H "Accept: application/x-yaml" \
> -b ~/cookies.txt  -d client='local' \
> -d tgt='test2.nginxs.net' \
> -d fun='state.sls'  -d arg='sysctl' -d saltenv=test
```

return:
```
- test2.nginxs.net:
  - No matching sls found for 'sysctl' in env 'base'`
```

--
Hello, where do I go wrong

--
Version: 
[root@test1 ~]#  salt  --versions-report  
           Salt: 2015.5.10
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: 2.2.1
        timelib: Not Installed
       dateutil: 1.4.1

**Comment by whiteinge** [comment]
`saltenv` is a kwarg to the various state functions so the syntax would be:
```
curl  -k https://localhost:8000 \
> -H "Accept: application/x-yaml" \
> -b ~/cookies.txt  -d client='local' \
> -d tgt='test2.nginxs.net' \
> -d fun='state.sls'  -d arg='sysctl' -d arg=saltenv=test
```

Or is JSON format which may be a bit less odd:
```
curl  -k https://localhost:8000 \
-H "Accept: application/x-yaml" \
-H "Content-type: application/json" \
-b ~/cookies.txt -d '
[{
    "client": "local",
    "tgt": "test2.nginxs.net",
    "fun": "state.sls",
    "kwarg": {
        "mods": "sysctl",
        "saltenv": "test"
    }
}]
'
```

**Comment by bashhu** [comment]
you are right. Thank you.
