### ISSUE TITLE
dockercompose module is missing docker-compose down command 

### ISSUE THREAD

**Issue by sam0104** [vmware-archive/salt-api#184]
dockercompose module is missing docker-compose down command  which actually takes care of deletion of docker container as well as network associated with it. Without dockercompose down I have to delete the container and then find the network associated with it and then delete it manually . Which is a complicated process. 

Please provide the dockercompose.down   as part of dockercompose module.

**Comment by terminalmage** [comment]
I think you have opened this report against the wrong repo. Can you please close this and open an issue on https://github.com/saltstack/salt ?

When you do, please mention @jeanpralo, who wrote that module.

**Comment by sam0104** [comment]
closing this as new issue is open : https://github.com/saltstack/salt/issues/47686
