### ISSUE TITLE
Add docs for configuring Salt for use with the rest_cherrypy netapi module

### ISSUE THREAD

**Issue by whiteinge** [vmware-archive/salt-api#23]
The rest_cherrypy module should explain that eauth must be configured and in use.

**Comment by kaptk2** [comment]
Some examples would be great as well to go along with this.

**Comment by whiteinge** [comment]
I realized this ticket was pretty vague since required Salt configuration will vary from netapi module to netapi module. I've updated it accordingly. Currently the only Salt-specific setting not mentioned in the docs is use of Salt's eauth system. I'll get it added.

**Comment by whiteinge** [comment]
@kaptk2 If there's anything else in particular you think would be helpful, I would appreciate your thoughts.
