### ISSUE TITLE
Stream responses from Salt

### ISSUE THREAD

**Issue by whiteinge** [vmware-archive/salt-api#25]
Salt returns can be iterative; we need to utilize that and stream the responses to execution requests as we get them back from minions.

**Comment by SEJeff** [comment]
iterative meaning returning a generator?

**Comment by whiteinge** [comment]
Yes. Though streaming responses carry caveats. It may be better to add a websockets netapi module. In either case we need a better mechanism than the current one to return very large responses from Salt. Perhaps simply paginating when doing job lookups.

**Comment by whiteinge** [comment]
Closing until we have more concrete use-cases be it performance (large returns) or usability (displaying data as it comes in), etc. Streaming an HTTP response is nice and low-tech but puts a large burden on the consumer to be able to intelligently parse a JSON stream. A websockets module is an obvious tack. Paginating responses is an entirely different issue.
