### ISSUE TITLE
'Setup.py build' Doesn't Copy rest_cherrypy Directory

### ISSUE THREAD

**Issue by dthom91** [vmware-archive/salt-api#27]
This occurs when building from master, or from the v0.7.1 tarball, but not from develop.

Example of setup.py output for master: http://pastebin.com/xAjT3wpR

Example for develop: http://pastebin.com/CP7zwwGz

**Comment by thatch45** [comment]
Thanks for the heads up, we will have a new release out soon with this fix

**Comment by whiteinge** [comment]
This should be fixed in the 0.7.5 tarball.
