### ISSUE TITLE
Salt-api does nothing. Please help me to configure the master

### ISSUE THREAD

**Issue by PierreR** [vmware-archive/salt-api#29]
I don't really see how to start the rest_cherrypy netapi module ...

What needs to be added to the master config file exactly so that he command 'salt-api' start the rest server ?

```
rest_cherrypy:
  - port: 8000
```

or does it need to be wrapped with "saltapi" or "netapi" ?

I am using the latest github src.

Thanks for your help.

**Comment by whiteinge** [comment]
The docs for the rest_cherrypy netapi module has an example of the required configuration near the top. The configuration is a dictionary though so you'll need to remove the dash in front of `port` in your example above.

tl;dr: port is always required, and _either_ debug or specifying SSL certs is required.

http://salt-api.readthedocs.org/en/latest/ref/netapis/all/saltapi.netapi.rest_cherrypy.html

**Comment by PierreR** [comment]
Thanks ! That what's my problem. I just had to remove the dash.
