### ISSUE TITLE
Add note about jQuery adding brackets to the ``arg`` param

### ISSUE THREAD

**Issue by whiteinge** [vmware-archive/salt-api#30]
jQuery (following the PHP/RoR convention) automatically adds empty brackets to the name of a param when using `x-www-form-urlencoded` if you pass that param more than once. We should add a small warning to the docs about this.

http://api.jquery.com/jQuery.param/

Thanks to xt on IRC for the report.

**Comment by SEJeff** [comment]
The doc being to set the `Content-Type: application/json` in the client hitting the api?

**Comment by whiteinge** [comment]
Sending JSON is definitely preferable and recommending that is also preferable to warnings about specific libs.

**Comment by whiteinge** [comment]
Added in 109f38b.
