### ISSUE TITLE
Minions in Python-API case sensitive, in bash-cmd not

### ISSUE THREAD

**Issue by vovcu** [vmware-archive/salt-api#32]
Hi, hope here is the right location for this "bug"-report.

I noticed if I call a cmd on a server from within Python

``` python
  import salt.client
  saltclient = salt.client.LocalClient()
  saltclient.cmd('salttest*', 'test.ping')
```

it won't work if the server is registered as "Salttest" or "SALTTEST".

Within the bash-cmd there is no case sensitivity. 

I don't know if this is intended or a "bug". I only think it would be more clear if you can write within Python the same way you write it in bash. As I store server-names in a DB (NC) I used expr_form='pcre' and put the names in a regex to get around this.

Marius

**Comment by whiteinge** [comment]
This bug should be filed on the Salt project instead. That said, thanks for finding this as it will affect the salt-api project too since we access Salt via the LocalClient interface. :)

**Comment by thatch45** [comment]
no case sensitivity on the command line? Thats not good, lemme check

**Comment by thatch45** [comment]
I can't reproduce this, the command line is clearly case sensitive

**Comment by vovcu** [comment]
Hi, tried it again. It's clearly case insensitive, partially. At least mine. I've got version 0.11.1 installed.

I got one server which is registered in upper-case-letters to salt-master. Now I can trigger following commands succesfully:
salt 'SERVER01_' test.ping
salt 'server01_' test.ping

Both work. This, by my understanding, is okay, as there is no sense in having two server with the same name, only distinguishable by case sensitivity. But if I use the salt Python API I have to write case sensitive.

This will work:
saltclient.cmd('SERVER01*', 'test.ping')

This won't work:
saltclient.cmd('server01*', 'test.ping')

Ok, now after even more testing I found out following behaviour. That's some kind of funny. 

Servers named with upper-case-letters, ex.: "SERVER1", "SERVER2", can be addressed like "server1" or "SERVER1". But servers registered with the master in lower-case are only callable with lower-case letters. Python API calls have to be case-sensitive.

Marius

**Comment by thatch45** [comment]
@vovcu, what is your OS, locale and salt-call --versions-report output on the minion?

**Comment by vovcu** [comment]
@thatch45 Hi, Ubuntu 12.04, en_US.UTF-8, salt-call on one of the servers (all servers with identical installation):
XXX:            Salt: 0.11.0
XXX:          Python: 2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)]
XXX:          Jinja2: 2.6
XXX:        M2Crypto: 0.21.1
XXX:  msgpack-python: 0.1.12
XXX:    msgpack-pure: not installed
XXX:        pycrypto: 2.3
XXX:          PyYAML: 3.10
XXX:           PyZMQ: 2.2.0.1

Sorry, for the "XXX", but those are production servers. The Minion is registered with an upper-case name to the master. I can call them lower-case and upper-case. The minions registered lower-case are callable only lower-case. I would not call it a major bug, but it's some kind of funny. At the moment I am struggeling even more with an Win32 service. 

Thanks.

**Comment by thatch45** [comment]
hmm, I still can't reproduce this one, and everything looks fine on your system. Also this is interesting because the command line uses the api directly
