### ISSUE TITLE
Using cmd.run with a file path as an argument

### ISSUE THREAD

**Issue by PierreR** [vmware-archive/salt-api#34]
I am not sure if this is intended or not.

If I run a `cmd.run` on a file I have got a python error from the minion saying that the directory does not exist (which is right because it is a file)

I am trying this via SaltUI:
`cmd.run` `ls /etc/salt` --> works fine
`cmd.run` `cat /etc/salt/master` --> failed

I have not tried it with curl so I cannot say for sure that the issue is not related to the UI.

As an obvious note, it does work using the salt command line 

Maybe I miss the doc that describes this limitation ?

**Comment by whiteinge** [comment]
If you're doing this from salt-ui, there is an open issue, saltstack/salt-ui#17, about how best to properly handle arguments. Currently it's just doing a naive split on whitepsace. salt-api should be able to handle this without issue:

``` bash
% curl -sS localhost:8000 -H 'Accept: application/x-yaml' -d client='local' -d tgt='*' -d fun='cmd.run' -d arg='cat /home/shouse/tmp/venvs/salt/etc/salt/master'
return:
- {ms-0: "##### Primary configuration settings #####\n
...
```

**Comment by PierreR** [comment]
Yep this is a Salt-UI problem.
