### ISSUE TITLE
salt-api package isn't in package repositories

### ISSUE THREAD

**Issue by SEJeff** [vmware-archive/salt-api#47]
Is it at a state where a fledgling release could be made yet?

**Comment by herlo** [comment]
Yes, it is. This package is actually in review for RPM.
https://bugzilla.redhat.com/show_bug.cgi?id=913296

Cheers,

herlo

**Comment by whiteinge** [comment]
There are also PPAs: https://launchpad.net/~saltstack/+archive/salt

**Comment by holmboe** [comment]
Not to forget the most important repository of all, the PyPI! :tada: 

https://pypi.python.org/pypi/salt-api

**Comment by whiteinge** [comment]
Reopening as a reminder to add this to the docs.  :-)
