### ISSUE TITLE
CherryPy3 needed for Ubuntu 12.04 (cherrypy2 does not work)

### ISSUE THREAD

**Issue by stevepacker** [vmware-archive/salt-api#48]
When getting salt-api installed on Ubuntu 12.04 x86_64, I also installed CherryPy as was recommended in the documentation (<code>sudo apt-get install python-cherrypy</code>) and when trying to start salt-api it would silently fail.  This was fixed by removing <code>python-cherrypy</code> (v2.3.0-3build1 at the time of this ticket) and installing <code>python-cherrypy3</code> (v3.2.2-2) instead.

**Comment by whiteinge** [comment]
Thanks for the report! The Ubuntu-specific detail is very helpful.

**Comment by ghost** [comment]
which one should the ubuntu package recommend? cherrypy is still optional, not required, correct?

**Comment by whiteinge** [comment]
CherryPy is optional. We need to recommend `python-cherrpy3`.
