### ISSUE TITLE
traceback when running salt-api unprivileged

### ISSUE THREAD

**Issue by SEJeff** [vmware-archive/salt-api#52]
Should be easy to fix:

``` bash
[jeff@omniscience salt-ui]$ salt-api -l debug
[INFO    ] Loaded configuration file: /etc/salt/master
[DEBUG   ] Created pidfile: /var/run/salt-master.pid
[DEBUG   ] Failed to set the ownership of PID file /var/run/salt-master.pid to user root
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 47, in set_pidfile
    os.chown(pidfile, uid, gid)
OSError: [Errno 1] Operation not permitted: '/var/run/salt-master.pid'
Failed to set the ownership of PID file /var/run/salt-master.pid to user root
```

**Comment by whiteinge** [comment]
Ah, interesting. That should be a `salt-api.pid` file instead. Looks like I'm using the `PidfileMixin` incorrectly. Thank you for the find!

**Comment by s0undt3ch** [comment]
This is weird. The [default pidfile name is being computed](https://github.com/saltstack/salt/blob/develop/salt/utils/parsers.py#L373) ... 

**Ah!**, I think I know what's going on, _hint, hint_, default config values.... I can take care of this if you don't...

**Comment by s0undt3ch** [comment]
There's actually 2 places where this could be fixed. The proper one, salt(but we should be careful there) and salt-api(simpler but does not solve the problem at it's root)....

**Comment by s0undt3ch** [comment]
#53 fixes the above `salt-api.pid` issue. I won't fix the permissions issue(yet).

**Comment by s0undt3ch** [comment]
That traceback is shown as part of the debug message, **if** the debug level is enabled, if not, you just see the permissions message.

So I think this is fixed? @SEJeff ?

**Comment by whiteinge** [comment]
Thanks, @s0undt3ch !

**Comment by s0undt3ch** [comment]
No problem!
