### ISSUE TITLE
Concurrent logins cause 500 errors

### ISSUE THREAD

**Issue by sfdc-kho** [vmware-archive/salt-api#61]
I am noticing 500 errors when trying to login concurrently using pam as the external auth. The log message is:

```
127.0.0.1 - - [13/Mar/2013:08:05:26] "POST /login HTTP/1.1" 500 37 "" "curl/7.21.4 (universal-apple-darwin11.0) libcurl/7.21.4 OpenSSL/0.9.8r zlib/1.2.5"
[CRITICAL] Authentication module threw an exception: argument 1: <type 'exceptions.TypeError'>: expected PamHandle instance instead of PamHandle
[CRITICAL] Authentication module threw an exception: argument 1: <type 'exceptions.TypeError'>: expected PamHandle instance instead of PamHandle
[CRITICAL] Authentication module threw an exception: argument 1: <type 'exceptions.TypeError'>: expected PamHandle instance instead of PamHandle
[CRITICAL] Authentication module threw an exception: argument 1: <type 'exceptions.TypeError'>: expected PamHandle instance instead of PamHandle
127.0.0.1 - - [13/Mar/2013:08:05:26] "POST /login HTTP/1.1" 500 37 "" "curl/7.21.4 (universal-apple-darwin11.0) libcurl/7.21.4 OpenSSL/0.9.8r zlib/1.2.5"
Traceback (most recent call last):
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 313, in 'calling callback function'
  File "/Library/Python/2.7/site-packages/salt/auth/pam.py", line 122, in my_conv
    p_response[0] = cast(addr, POINTER(PamResponse))
  File "_ctypes/callbacks.c", line 313, in 'calling callback function'
TypeError:   File "/Library/Python/2.7/site-packages/salt/auth/pam.py", line 122, in my_conv
incompatible types, LP_PamResponse instance instead of LP_PamResponse instance    p_response[0] = cast(addr, POINTER(PamResponse))
TypeError: incompatible types, LP_PamResponse instance instead of LP_PamResponse instance
```

To reproduce:
1. Start salt master and salt api
2. Generate load against salt-api using multiple processes all performing:

```
curl -sik -d "username=<user>&password=<password>&eauth=pam" "http://localhost:8000/login" 
```

Monitor logs and curl output. The curls will start returning:

```
HTTP/1.1 500 Internal Server Error
Content-Length: 37
Vary: Accept-Encoding
X-Auth-Token: 144a00d097bc58749cf816f2443b6086796c7716
Allow: GET, HEAD, POST
Date: Wed, 13 Mar 2013 15:05:02 GMT
Server: CherryPy/3.2.2
Content-Type: application/json
Set-Cookie: session_id=144a00d097bc58749cf816f2443b6086796c7716; expires=Thu, 14 Mar 2013 01:05:02 GMT; Path=/

{"status": 500, "message": "'token'"}
```

I am running salt-api 0.7.5 on OSX but I have also seen the same issue on RHEL6 inside a vagrant instance. Salt master is on version 0.13.1-45-gd52d617. CherryPy is 3.2.2.

**Comment by whiteinge** [comment]
Are you trying to auth against PAM as the root user by any chance? That error looks familiar...

**Comment by sfdc-kho** [comment]
Not root. Just a regular unprivileged user.

**Comment by whiteinge** [comment]
Can you try auth'ing with Salt at the CLI with those same credentials and let me know what Salt outputs? Something like:

``` bash
salt -a pam '*' test.ping
```

**Comment by whiteinge** [comment]
Edit: I suppose that may be tough to do concurrently...

**Comment by sfdc-kho** [comment]
Interesting. I tried your suggestion and it appears that eventually salt will hang on all but one process.

Here's the script:

```
#! /bin/bash

while true; do
    /usr/bin/expect -c 'spawn /usr/local/bin/salt -a pam --out json \* test.ping;  expect "username:" { send "<user>\r" }; expect "password:" { send "<password>\r" }; interact'
done
```

**Comment by whiteinge** [comment]
Great test. Thanks for that!

I'm getting mixed results trying to reproduce but I think it's specific to my setup here. I'll follow up on this as soon as I can. We definitely need to have working concurrent authentication!

**Comment by sfdc-kho** [comment]
Better stacktrace from OSX:

```
Traceback (most recent call last):
  File "/Users/kim.ho/git/salt/salt/auth/__init__.py", line 73, in __auth_call
    return self.auth[fstr](*fcall['args'], **fcall['kwargs'])
  File "/Users/kim.ho/git/salt/salt/auth/pam.py", line 147, in auth
    return authenticate(username, password, kwargs.get('service', 'login'))
  File "/Users/kim.ho/git/salt/salt/auth/pam.py", line 139, in authenticate
    retval = PAM_AUTHENTICATE(handle, 0)
ArgumentError: argument 1: <type 'exceptions.TypeError'>: expected PamHandle instance instead of PamHandle
```

My libpam info if this helps:

```
$ otool -L /usr/lib/libpam.dylib
/usr/lib/libpam.dylib:
    /usr/lib/libpam.2.dylib (compatibility version 3.0.0, current version 3.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.0.0)
```

Here's the one I get from RHEL6 inside vagrant:

```
Traceback (most recent call last):
  File "/vagrant/salt/salt/auth/__init__.py", line 73, in __auth_call
    return self.auth[fstr](*fcall['args'], **fcall['kwargs'])
  File "/vagrant/salt/salt/auth/pam.py", line 148, in auth
    return authenticate(username, password, kwargs.get('service', 'login'))
  File "/vagrant/salt/salt/auth/pam.py", line 133, in authenticate
    retval = PAM_START(service, username, pointer(conv), pointer(handle))
ArgumentError: argument 3: <type 'exceptions.TypeError'>: expected LP_PamConv instance instead of LP_PamConv

[CRITICAL] Authentication module threw an exception: argument 3: <type 'exceptions.TypeError'>: expected LP_PamConv instance instead of LP_PamConv
```

**Comment by whiteinge** [comment]
Thank you for the additional details! We're all at PyCon this weekend but we'll take a closer look at this once the conference is over.

**Comment by thatch45** [comment]
We have been looking into this and have not been able to reproduce it yet. We are working on some patches to give you to try.

**Comment by sfdc-kho** [comment]
I seem to have fixed the issue that I'm seeing with this patch[1] but it's unclear to me why it fixes the issue. All I've done is force cast to the same type rather than using POINTER(<type>) to create a ctype even though they should be the same thing[2]. Hopefully, someone familiar with python/ctypes can shed some light on whether this a configuration problem with our environments.

[1]http://pastebin.com/LLnhnuxb
[2]http://docs.python.org/2/library/ctypes.html

**Comment by sfdc-kho** [comment]
In RHEL6, I'm still getting this error but it's much less frequent: 

```
[CRITICAL] Authentication module threw an exception: incompatible types, CFunctionType instance instead of CFunctionType instance
Traceback (most recent call last):
  File "/vagrant/salt/salt/auth/__init__.py", line 73, in __auth_call
    return self.auth[fstr](*fcall['args'], **fcall['kwargs'])
  File "/vagrant/salt/salt/auth/pam.py", line 150, in auth
    return authenticate(username, password, kwargs.get('service', 'login'))
  File "/vagrant/salt/salt/auth/pam.py", line 131, in authenticate
    conv = PamConv(my_conv, 0)
TypeError: incompatible types, CFunctionType instance instead of CFunctionType instance
```

The RHEL6 environment is running python 2.6.6 whereas OSX is running 2.7.3

**Comment by whiteinge** [comment]
@sfdc-kho thank you for the patch! This is a bit out of my wheelhouse so I've run this past @thatch45 and he'll follow-up a bit later today.

**Comment by thatch45** [comment]
These additions look safe, but I am not sure why the concurrency is giving us this problem yet. I would say that we should add this patch and have a fallback try/except that will run a few retries until we can figure out the underlying problem.
I will open an issue on saltstack/salt to track this

**Comment by sfdc-kho** [comment]
Hey guys,

Just wanted to touch base on where we are on this. I don't suppose anyone else has had any luck reproducing this issue either through salt-api or through the salt client directly? Are we going to proceed with patching up the salt module in the interim?

**Comment by thatch45** [comment]
Sorry about the slow repsponses here, lets patch it up for now. Do you want to open a pull req?

**Comment by sfdc-kho** [comment]
Will do. I'll also work in the try/except retry logic as well.

**Comment by thatch45** [comment]
Thanks! I greatly appreciate it!

**Comment by sfdc-kho** [comment]
I've done a bit more digging into this issue and I think I've managed to create a reproducible test case. It seems to have something to do with concurrent auth module loading. 

```
from ctypes import *
import salt.auth
import ast, traceback

if __name__ == '__main__':
    opts = ast.literal_eval("{ 'external_auth': {'pam': {'service': ['.*']}}, 'extension_modules': ''}")
    auth = salt.auth.LoadAuth(opts)

    handle = auth.auth['pam.PamHandle']()
    print "Does handle match arg type? {0}".format(type(handle) == auth.auth['pam.PAM_AUTHENTICATE'].argtypes[0])

    salt.auth.LoadAuth(opts)
    print "Does handle match arg type? {0}".format(type(handle) == auth.auth['pam.PAM_AUTHENTICATE'].argtypes[0])
    try:
        auth.auth['pam.PAM_AUTHENTICATE'](handle, 0)
    except ArgumentError:
        traceback.print_exc()

    print "Now try to force cast"
    auth.auth['pam.PAM_AUTHENTICATE'](cast(addressof(handle), POINTER(auth.auth['pam.PAM_AUTHENTICATE'].argtypes[0])).contents, 0)
    print "Called PAM_AUTHENTICATE successfully"
```

On both our RHEL6 and OSX machines, this gives:

```
[vagrant@piab1-saltm1-1-piab salt-api]$ python scripts/test.py 
Does handle match arg type? True
Does handle match arg type? False
Traceback (most recent call last):
  File "scripts/test.py", line 20, in <module>
    auth.auth['pam.PAM_AUTHENTICATE'](handle, 0)
ArgumentError: argument 1: <type 'exceptions.TypeError'>: expected PamHandle instance instead of PamHandle
Now try to force cast
Called PAM_AUTHENTICATE successfully
```

If loading is in fact the root cause of the issue, the most straight-forward fix would be stop reloading auth in /login. We could also remove the hack in auth/pam. Thoughts? I've tried a patch locally and it seems to be harmless and actually seems to result in slight better login throughput (not that login performance is a huge bottleneck)

**Comment by whiteinge** [comment]
Interesting find! Aside from an apparent concurrency problem in the loader, it does make sense to load the auth module just one time anyway. Is the above commit what you had in mind?

**Comment by whiteinge** [comment]
BTW, I can reproduce the same output from running your script on both Fedora 17 and Ubuntu Lucid.

**Comment by sfdc-kho** [comment]
Yes that's exactly what I was thinking. I will submit a pull for reverting the earlier hack. Resolving this issue. I'm not sure if there's a larger loader bug here (or whether loader is simply not meant to be used like this) but will leave to you guys to make that call.

**Comment by whiteinge** [comment]
Thank you for your work tracking this down!
