### ISSUE TITLE
salt-api generates constant internal server errors on a fresh install

### ISSUE THREAD

**Issue by cmeisinger** [vmware-archive/salt-api#67]
Salt-master/salt-api installed via the EPEL repo (salt-master tested on epel/epel-testing versions).
Sending the following curl command results in an internal server error (all requests generate the same error).
    curl -sik -d "username=USERNAME&password=PASSWORD&eauth=pam" "http://localhost:8000/login"

Generates the following error...

https://gist.github.com/cmeisinger/5275275

External auth is configured in salt-master (tested via salt -a pam * test.ping).

**Comment by whiteinge** [comment]
This has been fixed in the current development version. A workaround (if you're running in an otherwise secure environment) is to disable SSL by setting `debug: true` under the `rest_cherrypy` section in your master config. Or you can install the development version from source.

**Comment by cmeisinger** [comment]
Confirmed as working. :)
