### ISSUE TITLE
Doc (or lack of) for more complex commands

### ISSUE THREAD

**Issue by PierreR** [vmware-archive/salt-api#70]
Is it currently possible to execute the following through the API ?

```
salt '*' cmd.exec_code ruby 'puts "cheese"'
```

If so how ? I have been trying some combination using `-d arg='[]'` without much success

As a general case, I am not sure I can make any arg using `=` at work.

Should I use an external json data file to do this ? Is this currently working through the salt-ui ?

While trying, I get alot of `401` where the issue is not an authentication one.

I know there are a couple of related issues in saltstack but I cannot find out what the current status is. Any pointer appreciated.

Thanks

**Comment by PierreR** [comment]
Ok this works fine with an external json file such as:

```
[
    {
        "client": "local",
        "tgt": "*",
        "fun": "network.ip_addrs",
        "arg": [
            "interface=eth0"
        ]
    }
]
```

**Comment by whiteinge** [comment]
Glad you got it. Using JSON for the input is much more straightforward. That said, this command should work:

``` bash
curl -sS localhost:8000 \
    -H 'Accept: application/x-yaml' \
    -d client='local' \
    -d tgt='*' \
    -d fun='cmd.exec_code' \
    -d arg='ruby' \
    -d arg='puts "cheese"'
```
