### ISSUE TITLE
CherryPy is required, not optional

### ISSUE THREAD

**Issue by ghost** [vmware-archive/salt-api#71]
CherryPy is listed in opt_requirements, but when I remove it I get a traceback:

```
[DEBUG   ] Failed to import netapi rest_cherrypy, this is most likely NOT a problem:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/salt/loader.py", line 567, in gen_functions
    ), fn_, path, desc
  File "/usr/lib/pymodules/python2.7/saltapi/netapi/rest_cherrypy/__init__.py", line 27, in <module>
    from . import app
  File "/usr/lib/pymodules/python2.7/saltapi/netapi/rest_cherrypy/app.py", line 137, in <module>
    import cherrypy
ImportError: No module named cherrypy
```

**Comment by whiteinge** [comment]
CherryPy is required for the `rest_cherrpy` module but it is not required for `salt-api`. In the same vein that the Python MySQL bindings are required for Salt's MySQL execution module but not required for Salt. This will be somewhat more obvious once `salt-api` has more than one module. :-P

The above traceback shows up in the logging output, yes? If you have a `rest_cherrpy` section in your master config it is assumed you do want to run that module and it will log (hopefully) helpful error messages. If you don't have that section in your master config then the loader will skip over that module silently.

**Comment by ghost** [comment]
I have zero config in my salt master. I expect salt-api would just do nothing and exit, which is exactly what it does when I have either cherrypy or cherrypy3 installed, but with neither one I get this traceback. I'm only doing this on the command line.  if this is acceptable to you it is acceptable to me; I truly know nothing of salt-api.

**Comment by whiteinge** [comment]
Bah, you're right! This isn't working exactly as I would like. Looks like I broke my friendlier error-checking when I pulled the standalone WSGI app out of the main module.

@seanchannel thank you, sir!
