### ISSUE TITLE
Quiet CherryPy Output in Daemon Mode

### ISSUE THREAD

**Issue by kaptk2** [vmware-archive/salt-api#83]
When salt-api is run in daemon mode (salt-api -d) the logging needs to be output some place other than stdout. Perhaps tied into salt logging.

**Comment by whiteinge** [comment]
Thanks for the report. I'll take a closer look at this.

I _think_ the fix is in `rest_cherrypy/__init__.py` after instantiating the application object. We should be able to modify the `application.log` object to tie into Salt's logger.

**Comment by jalons** [comment]
I also see this issue, only mine manifests in IOError: [Errno 5] Input/output error if the controlling terminal that spawned the salt-api goes away for any request to the API that has returns (i.e., test.ping's return of True on success will result in IOError's and cherrypy throwing 500 errors as it evidently can not print the output anywhere.

**Comment by whiteinge** [comment]
Thanks for the additional report. We're about to make some architectural changes to salt-api and we'll get this addressed as soon as that happens.

**Comment by whiteinge** [comment]
Quick update: CherryPy will no longer output to the screen as of 4dd9e97 unless debug=True. That said there are still many, many print statements within Salt itself that will cause the IOError (such as most (all?) runner modules as well as a method or two in LocalClient). I'll leave this ticket open until we can figure out how best to address those as well.

**Comment by whiteinge** [comment]
I'm going to close this for now. I believe any remaining issues here are due to saltstack/salt#5700. If anyone sees otherwise, please reopen this ticket.
