### ISSUE TITLE
PID file issues

### ISSUE THREAD

**Issue by PAStheLoD** [vmware-archive/salt-api#85]
Hello!

I'm testing 0.8.1, and while using the -d daemon mode and the --pid-file option, it seems that there are a few problems:
- sending SIGTERM to main salt-api process doesn't result in a complete salt-api shutdown
- the PID file remains after salt-api has shut itself down

So it's currently quite hard to use it as a proper "unix daemon".

**Comment by whiteinge** [comment]
@PAStheLoD thanks for the report! Can you verify the above pull req fixes the issue?

**Comment by whiteinge** [comment]
Closing. Please feel free to reopen if the issue isn't resolved.

**Comment by PAStheLoD** [comment]
Hello! Thanks and sorry for lack of feedback. I'll report anything I encounter, when I'll get some time to further play with the Salt API.
