### ISSUE TITLE
grains.setval multiple argumnets 

### ISSUE THREAD

**Issue by kerncore** [vmware-archive/salt-api#96]
hi,

I try to assign grains to minion with following request : 

curl -si https://localhost:8000/run  -H 'Accept: application/x-yaml' \
       -H "X-Auth-Token: TOKEN1234" \
       -d client='local' \ 
       -d fun='grains.setval' \
       -d tgt='foo'  \
       -d arg='Type=[{"WEB","NET"}]'

return:
- foo: 'Missing arguments executing "grains.setval":
  ArgSpec(args=[''key'', ''val''], varargs=None, keywords=None, defaults=None)'

How is possible to assign grains to minion pass-through salt-api ?

Thanks

**Comment by whiteinge** [comment]
The `setval` function is expecting the `key` and `val` to be spread across two arguments like this: `-d arg='Type' -d arg='[{"WEB","NET"}]'`.

The equivalent call at the CLI would be `salt 'foo' grains.setval 'Type' '[{"WEB","NET"}]'`.

**Comment by whiteinge** [comment]
@kerncore Were you able to resolve this?
